### ISSUE TITLE
Homewhiz cloud

### ISSUE THREAD

**Issue by teqali** [rowysock/home-assistant-HomeWhiz#103]
Bu hata, özel bir entegrasyondan kaynaklanmıştır.

Logger: homeassistant.config_entries
Source: custom_components/homewhiz/__init__.py:72 
Integration: HomeWhiz (documentation, issues) 
First occurred: 22:08:39 (1 occurrences) 
Last logged: 22:08:39

Error setting up entry Kurutma for homewhiz
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/homewhiz/__init__.py", line 34, in async_setup_entry
    return await setup_cloud(entry, hass)
  File "/config/custom_components/homewhiz/__init__.py", line 77, in setup_cloud
    _lazy_install_awsiotsdk()
  File "/config/custom_components/homewhiz/__init__.py", line 72, in _lazy_install_awsiotsdk
    raise RequirementsNotFound(DOMAIN, [pkg])
homeassistant.requirements.RequirementsNotFound: Requirements for homewhiz not found: ['awsiotsdk'].

**Comment by teqali** [comment]
2023-01-31 22:17:06.128 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration homewhiz which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-31 22:19:38.459 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Kurutma for homewhiz
File "/config/custom_components/homewhiz/__init__.py", line 34, in async_setup_entry
File "/config/custom_components/homewhiz/__init__.py", line 77, in setup_cloud
File "/config/custom_components/homewhiz/__init__.py", line 72, in _lazy_install_awsiotsdk
homeassistant.requirements.RequirementsNotFound: Requirements for homewhiz not found: ['awsiotsdk'].
2023-01-31 22:35:38.159 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Kurutma for homewhiz
File "/config/custom_components/homewhiz/__init__.py", line 34, in async_setup_entry
File "/config/custom_components/homewhiz/__init__.py", line 77, in setup_cloud
File "/config/custom_components/homewhiz/__init__.py", line 72, in _lazy_install_awsiotsdk
homeassistant.requirements.RequirementsNotFound: Requirements for homewhiz not found: ['awsiotsdk'].
2023-01-31 22:41:28.754 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Klima for homewhiz
File "/config/custom_components/homewhiz/__init__.py", line 34, in async_setup_entry
File "/config/custom_components/homewhiz/__init__.py", line 77, in setup_cloud
File "/config/custom_components/homewhiz/__init__.py", line 72, in _lazy_install_awsiotsdk
homeassistant.requirements.RequirementsNotFound: Requirements for homewhiz not found: ['awsiotsdk'].

**Comment by TechHummel** [comment]
We can't offer help in languages other than English. There is also already another issue #97 about this particular error.
