### ISSUE TITLE
AWS_IO_DNS_QUERY_FAILED

### ISSUE THREAD

**Issue by elektrolitr** [rowysock/home-assistant-HomeWhiz#115]
I run into issue with AWS connection for two times in a week
After that, it's running fine for another two weeks so it looks the issue is sporadic. 
Resetting HASS or Homewhiz addon helps to mitigate the issue. But correct handling of the issue and automatic reconnect would be nice. 

the log:
`2023-03-01 00:35:23.242 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/homewhiz/cloud.py", line 158, in refresh_connection
    await self.connect()
  File "/config/custom_components/homewhiz/cloud.py", line 102, in connect
    connection.connect().result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
awscrt.exceptions.AwsCrtError: AWS_IO_DNS_QUERY_FAILED: A query to dns failed to resolve.` 

After that, all update requests end with error because the MQTT connection is broken 

`2023-03-01 00:35:23.269 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 174, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.
2023-03-01 00:37:23.255 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 174, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.`

**Comment by elektrolitr** [comment]
Good thing is that I found how to recreate this event (thank you @scottbruns for the https://github.com/rowysock/home-assistant-HomeWhiz/pull/121, it really pushed me to the right path!)
If the internet connection is broken when AWS connection has to be renewed, the renewal process fails and doesn't restore 


I tested the #121  and it doesn't work :(

the logs are below
 
```
2023-04-26 20:31:03.204 INFO (MainThread) [custom_components.homewhiz] Setting up entry F999931386498761371494
2023-04-26 20:31:03.204 INFO (MainThread) [custom_components.homewhiz] Setting up cloud connection
2023-04-26 20:31:03.249 DEBUG (MainThread) [custom_components.homewhiz] Sensors: ['STATE', 'DISHWASHER_PROGRAM', 'SUB_STATE', 'DISHWASHER_DELAY', 'DISHWASHER_DURATION', 'DISHWASHER_REMAINING', 'SETTING_DETERGENT_TYPE', 'DISHWASHER_RINSE_AID_LEVEL', 'DISHWASHER_LIQUID_DETERGENT_LEVEL', 'DISHWASHER_WATER_HARDNESS']
2023-04-26 20:31:03.254 DEBUG (MainThread) [custom_components.homewhiz] Binary sensors: ['REMOTE_CONTROL', 'DISHWASHER_WARNING_NO_RINSE_AID', 'DISHWASHER_WARNING_NO_SALT', 'DISHWASHER_WARNING_NO_WATER', 'DISHWASHER_WARNING_CHECK_THE_FILTER', 'DISHWASHER_WARNING_DOOR_IS_OPEN', 'DISHWASHER_WARNING_CALL_SERVICE', 'DISHWASHER_LIQUID_DETERGENT_LOW']
2023-04-26 20:31:03.297 DEBUG (MainThread) [custom_components.homewhiz] Selects: ['STATE', 'DISHWASHER_PROGRAM', 'SETTING_DETERGENT_TYPE', 'DISHWASHER_RINSE_AID_LEVEL', 'DISHWASHER_LIQUID_DETERGENT_LEVEL', 'DISHWASHER_WATER_HARDNESS']
2023-04-26 20:31:03.322 DEBUG (MainThread) [custom_components.homewhiz] ACs: []
2023-04-26 20:31:03.369 DEBUG (MainThread) [custom_components.homewhiz] Switches: ['DISHWASHER_HYGIENE_INTENSE', 'DISHWASHER_STEAMGLOSS', 'DISHWASHER_DEEPWASH', 'DISHWASHER_FAST+', 'DISHWASHER_HALFLOAD', 'SETTING_AUTO_DOOR', 'SETTING_INNER_ILLUMINATION']
2023-04-26 20:31:03.414 INFO (MainThread) [custom_components.homewhiz] Connecting to F999931386498761371494
2023-04-26 20:31:04.135 DEBUG (MainThread) [custom_components.homewhiz] Credentials expire at: 2023-04-26 21:31:03
2023-04-26 20:31:04.615 DEBUG (MainThread) [custom_components.homewhiz] Subscribe to update result: {'packet_id': 1, 'topic': '$aws/things/F999931386498761371494/shadow/update/accepted', 'qos': <QoS.AT_LEAST_ONCE: 1>}
2023-04-26 20:31:04.689 DEBUG (MainThread) [custom_components.homewhiz] Subscribe to get result: {'packet_id': 2, 'topic': '$aws/things/F999931386498761371494/shadow/get/accepted', 'qos': <QoS.AT_LEAST_ONCE: 1>}
2023-04-26 20:31:04.690 DEBUG (MainThread) [custom_components.homewhiz] Force read result: {'packet_id': 3}
2023-04-26 20:31:04.691 DEBUG (MainThread) [custom_components.homewhiz] Get shadow result: {'packet_id': 4}
2023-04-26 20:31:04.691 DEBUG (MainThread) [custom_components.homewhiz] Set hass time interval update
...



...
2023-04-26 21:28:04.862 DEBUG (Dummy-3) [custom_components.homewhiz] Manually updated homewhiz data
2023-04-26 21:29:04.772 DEBUG (SyncWorker_7) [custom_components.homewhiz] Force read result: {'packet_id': 64}
2023-04-26 21:30:04.772 DEBUG (SyncWorker_8) [custom_components.homewhiz] Force read result: {'packet_id': 65}
2023-04-26 21:31:03.001 DEBUG (MainThread) [custom_components.homewhiz] Refreshing connection
2023-04-26 21:31:03.001 INFO (MainThread) [custom_components.homewhiz] Connecting to F999931386498761371494
2023-04-26 21:31:04.774 DEBUG (SyncWorker_4) [custom_components.homewhiz] Force read result: {'packet_id': 67}
2023-04-26 21:31:07.700 DEBUG (Dummy-3) [custom_components.homewhiz] Connection interrupted AWS_ERROR_MQTT_TIMEOUT: Time limit between request and response has been exceeded.
2023-04-26 21:31:08.011 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 863, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/homewhiz/cloud.py", line 179, in refresh_connection
    await self.connect()
  File "/config/custom_components/homewhiz/cloud.py", line 86, in connect
    credentials = await login(
  File "/config/custom_components/homewhiz/api.py", line 112, in login
    async with session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.arcelikiot.com:443 ssl:default [Try again]
2023-04-26 21:32:04.775 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 195, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.
2023-04-26 21:32:08.428 ERROR (MainThread) [metno] Access to https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/2.0/complete returned error 'ClientConnectorError'
2023-04-26 21:32:08.435 ERROR (MainThread) [homeassistant.components.met] Error fetching met data: Update failed: 
2023-04-26 21:33:04.776 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 195, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.
2023-04-26 21:34:04.778 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 195, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.
2023-04-26 21:35:04.779 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 195, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.
2023-04-26 21:36:04.780 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 195, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.
2023-04-26 21:37:04.781 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 195, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.
2023-04-26 21:38:04.783 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 195, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.
2023-04-26 21:39:04.784 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 195, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.
2023-04-26 21:40:04.786 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 195, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.
2023-04-26 21:41:04.788 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 195, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.
2023-04-26 21:42:04.790 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 195, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.
2023-04-26 21:43:04.790 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 195, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.
2023-04-26 21:44:04.792 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 195, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.
2023-04-26 21:45:04.794 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homewhiz/cloud.py", line 195, in force_read
    _LOGGER.debug(f"Force read result: {publish.result()}")
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/awscrt/mqtt.py", line 717, in publish
    packet_id = _awscrt.mqtt_client_connection_publish(self._binding, topic, payload, qos.value, retain, puback)
RuntimeError: 5131 (AWS_ERROR_MQTT_NOT_CONNECTED): The requested operation is invalid as the connection is not open.

```

**Comment by TechHummel** [comment]
Thanks for your feedback! #121 is supposed to cover DNS errors only, but not having an internet connection seems to cause a different error.
