### ISSUE TITLE
Can't connect to washing machine

### ISSUE THREAD

**Issue by pawelpolski** [rowysock/home-assistant-HomeWhiz#116]
have problem to connnect washing machine on raspberry pi via cloud, device is found but after that i get erron on logs:

Any ideas how to solve?

Logger: homeassistant.config_entries
Source: custom_components/homewhiz/__init__.py:72
Integration: HomeWhiz (documentation, issues)
First occurred: 16:49:53 (1 occurrences)
Last logged: 16:49:53

Error setting up entry Pralka for homewhiz
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/homewhiz/__init__.py", line 34, in async_setup_entry
    return await setup_cloud(entry, hass)
  File "/config/custom_components/homewhiz/__init__.py", line 77, in setup_cloud
    _lazy_install_awsiotsdk()
  File "/config/custom_components/homewhiz/__init__.py", line 72, in _lazy_install_awsiotsdk
    raise RequirementsNotFound(DOMAIN, [pkg])
homeassistant.requirements.RequirementsNotFound: Requirements for homewhiz not found: ['awsiotsdk'].

**Comment by TechHummel** [comment]
Please refer to #97
