### ISSUE TITLE
Problems on HomeWhiz afther update to the new version 

### ISSUE THREAD

**Issue by home89c3** [rowysock/home-assistant-HomeWhiz#129]
Hi , i update the home assistant component and now dosent want to set the temperature and dosent update the data .
I have a grunding AC  , integration is via cloud , local dosent work . 
Here is the log.
Any ideea what i can do ! please 
Logger: homeassistant.components.websocket_api.http.connection
Source: components/climate/__init__.py:613
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:22:22 (1 occurrences)
Last logged: 16:22:22

[546861325552] HomeWhizClimateEntity.async_set_temperature() got an unexpected keyword argument 'entity_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 216, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 613, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
TypeError: HomeWhizClimateEntity.async_set_temperature() got an unexpected keyword argument 'entity_id'

**Comment by TechHummel** [comment]
Hi 👋 
This was fixed with #124 (and is therefore a duplicate).
Please wait for a new tagged version or upgrade to main branch to fix this.
