### ISSUE TITLE
Unknown error occurred / Adding cloud device not possible

### ISSUE THREAD

**Issue by ede-kowalski** [rowysock/home-assistant-HomeWhiz#145]
Hi,

i have added my new device via homewhiz and its working on my phone.
So i tried to install and configure it in HA but getting the error: Unknown error occurred

In the log i can find:
`2023-07-28 14:10:05.230 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 181, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewhiz/config_flow.py", line 182, in async_step_provide_cloud_credentials
    return await self.async_step_select_cloud_device()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewhiz/config_flow.py", line 228, in async_step_select_cloud_device
    self._cloud_appliances = await fetch_appliance_infos(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewhiz/api.py", line 287, in fetch_appliance_infos
    resp = await make_api_get_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/homewhiz/api.py", line 214, in make_api_get_request
    if not contents["success"]:
           ~~~~~~~~^^^^^^^^^^^
KeyError: 'success'
`
Andy hints?
Thanks,
Ede

**Comment by TechHummel** [comment]
Hi Ede,
thanks for reporting this issue! 👍 
Could you please test if this issue still occurs with the latest beta release? Thanks!

**Comment by ede-kowalski** [comment]
Hi @TechHummel ,
unfortunately it don't seem to work.
I am getting an error message that not all needed fields are provided?
Regards,
Ede

**Comment by TechHummel** [comment]
There haven't been any changes recently, however the last official release was even older 😄 So I think you installed it correctly.
Can you tell me your device digital ID? What kind of device are you trying to add?

**Comment by ede-kowalski** [comment]
Hi, my model is 7188236670 its a dryer.
Can i send that id private?

**Comment by MaVE16** [comment]
<img width="1440" height="3120" alt="Image" src="https://github.com/user-attachments/assets/96264a53-ac7b-457b-bc00-4ff73b3924aa" />

Kann den Gefrierschrank nicht mehr einbinden...
