### ISSUE TITLE
Integration doesnt seem to get added

### ISSUE THREAD

**Issue by gust4vsson** [rowysock/home-assistant-HomeWhiz#2]
I added the repo in HACS and downloaded the integration.

Then I searched for it in integrations, found it, tried adding it and this dialogue shows up. I press save, nothing really happens and I can close the dialogue.

It does not do anything else than that.

![bild](https://user-images.githubusercontent.com/5673963/187999435-c9f34609-029f-4ba2-bfdb-ca82bfe2bea7.png)

**Comment by rowysock** [comment]
Currently, the window is empty. If you press "Submit" the integration will search for available devices, If it finds something it will be shown in the window. If it doesn't show anything probably no device is available. 

Have you managed to connect the device to HomeWhiz mobile app?
Is the device and HA in the bluetooth range?
You can also enable debug logging for this integration and see what's going on.

It'd be a good idea to add helpful messages to the window in the future, but I didn't have time to do that yet. You can give it a shot if you want.

**Comment by 0000vt** [comment]
Is the error 'unknown error occurred' in the integration screen also a notification of no device available? Or would it just stay blank?
I got this in the logs:
`Logger: aiohttp.server
Source: custom_components/HomeWhiz/homewhiz.py:59
Integration: HomeWhiz ([documentation](https://github.com/rowysock/HomeWhiz), [issues](https://github.com/rowysock/HomeWhiz/issues))
First occurred: 22:24:42 (16 occurrences)
Last logged: 22:26:44

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 205, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_flow.py", line 64, in async_step_confirm
    has_devices = await cast(
  File "/config/custom_components/HomeWhiz/config_flow.py", line 9, in _async_has_devices
    devices = await scan()
  File "/config/custom_components/HomeWhiz/homewhiz.py", line 59, in scan
    devices = await BleakScanner.discover()
  File "/usr/local/lib/python3.9/site-packages/bleak/backends/scanner.py", line 115, in discover
    async with cls(**kwargs) as scanner:
  File "/usr/local/lib/python3.9/site-packages/bleak/backends/scanner.py", line 95, in __aenter__
    await self.start()
  File "/usr/local/lib/python3.9/site-packages/bleak/backends/bluezdbus/scanner.py", line 88, in start
    self._bus = await MessageBus(bus_type=BusType.SYSTEM).connect()
  File "/usr/local/lib/python3.9/site-packages/dbus_next/aio/message_bus.py", line 122, in __init__
    super().__init__(bus_address, bus_type, ProxyObject)
  File "/usr/local/lib/python3.9/site-packages/dbus_next/message_bus.py", line 85, in __init__
    self._setup_socket()
  File "/usr/local/lib/python3.9/site-packages/dbus_next/message_bus.py", line 575, in _setup_socket
    raise err
  File "/usr/local/lib/python3.9/site-packages/dbus_next/message_bus.py", line 548, in _setup_socket
    self._sock.connect(filename)
FileNotFoundError: [Errno 2] No such file or directory`

**Comment by rowysock** [comment]
@0000vt This looks like a system configuration problem. Do you have a bluetooth and dbus configured on your machine? Is bluetooth available to HomeAssistant?

Also, this issue looks similar: https://github.com/home-assistant/core/issues/65834

**Comment by gust4vsson** [comment]
So sorry I'm late to reply. I just moved into the house and I have a lot of stuff going on.

I will be giving it a go later. Also I think my machine is a Cylinda so it probably isn't supported anyways. Is there a way for me to work out support for it?

**Comment by rowysock** [comment]
@gust4vsson The HomeWhiz application supports only a few different types of washing machines. Most of them fall under a "generic washing machine" type. This is a type of my washing machine, and this is a type I implemented in this integration. There is a great chance, that your washing machine even though it's a different model, is also a "generic washing machine" according to HomeWhiz. If it's not, it should be pretty easy to add support. 

For now, I'm closing the issue
