### ISSUE TITLE
Use bleak-retry-connector for Bluetooth connection

### ISSUE THREAD

**Issue by TechHummel** [rowysock/home-assistant-HomeWhiz#24]
We should use the bleak-retry-connector, so we don't have to rely on a fixed timeout. As an example, this module is used in the [eq3btsmart thermostat integration](https://github.com/dbuezas/eq3btsmart/blob/82c6cbdb72f7c44248409261321029535dc5a86c/custom_components/dbuezas_eq3btsmart/python_eq3bt/eq3bt/bleakconnection.py#L82).

**Comment by rowysock** [comment]
In the example you linked I'm not sure about `disconnected_callback `. After disconnecting, we want to connect again, however, in the example, only `schedule_update_ha_state` is invoked. Is it possible that `bleak-retry-connector` reconnects automatically?

**Comment by TechHummel** [comment]
I honestly don't know! I did not find any documentation for this module - I think this is still on the todo list!

**Comment by TechHummel** [comment]
So, I just had my homeassistant basically crash because of being flooded with the following error messages:
```
2022-11-30 09:23:52.060 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/homewhiz/__init__.py", line 84, in reconnect
    await self.client.stop_notify("0000ac02-0000-1000-8000-00805f9b34fb")
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 667, in stop_notify
    await self._backend.stop_notify(char_specifier)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 907, in stop_notify
    raise BleakError("Characteristic {} not found!".format(char_specifier))
bleak.exc.BleakError: Characteristic 0000ac02-0000-1000-8000-00805f9b34fb not found!
2022-11-30 09:23:52.060 ERROR (Thread-1 (_monitor)) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 172, in connect
    reply = await self._bus.call(
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 370, in call
    await future
  File "/usr/local/lib/python3.10/site-packages/dbus_fast/aio/message_bus.py", line 84, in write_callback
    self.offset += self.sock.send(self.buf[self.offset :])
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by TechHummel** [comment]
I found some more interesting logs:
```
[36m2022-11-30 09:13:33.063 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:13:34.121 DEBUG (MainThread) [custom_components.homewhiz] connected[0m
[31m2022-11-30 09:13:34.123 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/homewhiz/__init__.py", line 84, in reconnect
    await self.client.stop_notify("0000ac02-0000-1000-8000-00805f9b34fb")
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 667, in stop_notify
    await self._backend.stop_notify(char_specifier)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 917, in stop_notify
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] No notify session started[0m
[31m2022-11-30 09:13:38.739 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/homewhiz/__init__.py", line 84, in reconnect
    await self.client.stop_notify("0000ac02-0000-1000-8000-00805f9b34fb")
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 667, in stop_notify
    await self._backend.stop_notify(char_specifier)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 917, in stop_notify
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] No notify session started[0m
```

or

```
[36m2022-11-30 09:22:24.883 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.883 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.884 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.884 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.886 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.886 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.888 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.889 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.891 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.891 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.893 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.893 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.896 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.896 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.899 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.899 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.904 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.904 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.906 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.906 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.911 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.911 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.912 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.913 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.913 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.914 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.917 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.917 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.920 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.920 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.923 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.924 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.925 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.925 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.926 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.926 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.928 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.929 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.930 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.930 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.931 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.931 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.932 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.932 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.934 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.934 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.935 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.935 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.937 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.937 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.938 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.938 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.939 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.939 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.940 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.940 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.941 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.941 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.942 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.942 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.942 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.942 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.943 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.943 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.944 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.944 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.944 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.944 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.945 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.945 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.946 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.946 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.947 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.947 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.948 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.948 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.949 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.949 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.949 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.949 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.950 DEBUG (MainThread) [custom_components.homewhiz] Disconnected, reconnecting[0m
[36m2022-11-30 09:22:24.950 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.956 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.957 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.957 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.958 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.958 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.959 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.959 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.959 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.960 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[36m2022-11-30 09:22:24.960 DEBUG (MainThread) [custom_components.homewhiz] Trying to connect[0m
[33m2022-11-30 09:22:24.967 WARNING (MainThread) [custom_components.homewhiz] [org.bluez.Error.Failed] Operation already in progress[0m
[33m2022-11-30 09:22:24.968 WARNING (MainThread) [custom_components.homewhiz] [org.bluez.Error.Failed] Operation already in progress[0m
[33m2022-11-30 09:22:24.968 WARNING (MainThread) [custom_components.homewhiz] [org.bluez.Error.Failed] Operation already in progress[0m
[33m2022-11-30 09:22:24.969 WARNING (MainThread) [custom_components.homewhiz] [org.bluez.Error.Failed] Operation already in progress[0m
[33m2022-11-30 09:22:24.969 WARNING (MainThread) [custom_components.homewhiz] [org.bluez.Error.Failed] Operation already in progress[0m
[33m2022-11-30 09:22:24.969 WARNING (MainThread) [custom_components.homewhiz] [org.bluez.Error.Failed] Operation already in progress[0m
[33m2022-11-30 09:22:24.970 WARNING (MainThread) [custom_components.homewhiz] [org.bluez.Error.Failed] Operation already in progress[0m
[33m2022-11-30 09:22:24.970 WARNING (MainThread) [custom_components.homewhiz] [org.bluez.Error.Failed] Operation already in progress[0m
[33m2022-11-30 09:22:24.971 WARNING (MainThread) [custom_components.homewhiz] [org.bluez.Error.Failed] Operation already in progress[0m
[33m2022-11-30 09:22:24.971 WARNING (MainThread) [custom_components.homewhiz] [org.bluez.Error.Failed] Operation already in progress[0m
[33m2022-11-30 09:22:24.972 WARNING (MainThread) [custom_components.homewhiz] [org.bluez.Error.Failed] Operation already in progress[0m
[33m2022-11-30 09:22:24.972 WARNING (MainThread) [custom_components.homewhiz] [org.bluez.Error.Failed] Operation already in progress[0m
[33m2022-11-30 09:22:24.974 WARNING (MainThread) [custom_components.homewhiz] [org.bluez.Error.Failed] br-connection-canceled[0m
```
so it seems the timeout does not seem to work in all cases!

**Comment by TechHummel** [comment]
I saw you assigned the issue to yourself - thanks 👍! 
I did start trying out a couple of things - I pushed my branch (log_flooding) and will monitor my home assistant!

**Comment by rowysock** [comment]
I'm trying to use bleak_retry_connector with the example you linked, it works really nicely.
As I was implementing it initially I remember that the washing machine disconnected every 10 seconds or so, I don't see this with  bleak_retry_connector, however it disconnects eventually after a few minutes. I suspect that the device is just turning off. I'm trying to figure a way to reconnect when the device is available. I'm thinking about the `async_register_callback` from homeassistant bluetooth component
