### ISSUE TITLE
Detects AC on cloud but does not add

### ISSUE THREAD

**Issue by tnrclkr** [rowysock/home-assistant-HomeWhiz#70]
it detects AC on cloud connection but gives error as "unknown error occured" then not adding AC as entity.
![1](https://user-images.githubusercontent.com/48097971/209622121-3a58df58-233c-457d-b3b9-f18e3ecf1800.JPG)
![2](https://user-images.githubusercontent.com/48097971/209622125-f776b79b-052f-4edf-b738-78eb18eebaf2.JPG)

**Comment by fotisbaco** [comment]
I have excatly the same problem with a Oven

![homewhiz_error](https://user-images.githubusercontent.com/60899404/209623549-2ed90155-2e91-4236-a00c-d8a35dbefb0b.jpg)

**Comment by rowysock** [comment]
@tnrclkr @fotisbaco Please share the logs https://github.com/rowysock/home-assistant-HomeWhiz#retrieve-integration-logs

**Comment by tnrclkr** [comment]
This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/homewhiz/api.py:278
Integration: HomeWhiz (documentation, issues)
First occurred: 10:51:34 (2 occurrences)
Last logged: 10:51:42

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 281, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/homewhiz/config_flow.py", line 210, in async_step_select_cloud_device
    contents = await fetch_appliance_contents(
  File "/config/custom_components/homewhiz/api.py", line 278, in fetch_appliance_contents
    config=from_dict(ApplianceConfiguration, config), localization=localization
  File "/usr/local/lib/python3.10/site-packages/dacite/core.py", line 63, in from_dict
    value = _build_value(type_=field.type, data=transformed_value, config=config)
  File "/usr/local/lib/python3.10/site-packages/dacite/core.py", line 88, in _build_value
    return _build_value_for_union(union=type_, data=data, config=config)
  File "/usr/local/lib/python3.10/site-packages/dacite/core.py", line 99, in _build_value_for_union
    return _build_value(type_=types[0], data=data, config=config)
  File "/usr/local/lib/python3.10/site-packages/dacite/core.py", line 92, in _build_value
    return from_dict(data_class=type_, data=data, config=config)
  File "/usr/local/lib/python3.10/site-packages/dacite/core.py", line 63, in from_dict
    value = _build_value(type_=field.type, data=transformed_value, config=config)
  File "/usr/local/lib/python3.10/site-packages/dacite/core.py", line 88, in _build_value
    return _build_value_for_union(union=type_, data=data, config=config)
  File "/usr/local/lib/python3.10/site-packages/dacite/core.py", line 99, in _build_value_for_union
    return _build_value(type_=types[0], data=data, config=config)
  File "/usr/local/lib/python3.10/site-packages/dacite/core.py", line 92, in _build_value
    return from_dict(data_class=type_, data=data, config=config)
  File "/usr/local/lib/python3.10/site-packages/dacite/core.py", line 68, in from_dict
    raise WrongTypeError(field_path=field.name, field_type=field.type, value=value)
dacite.exceptions.WrongTypeError: wrong value type for field "progressVariables.autoOff.isExpandableBySwitch" - should be "Optional" instead of value "1" of type "int"

**Comment by rowysock** [comment]
@tnrclkr Thank you. What is your device's "Digital ID"? it can be found in the app device settings

**Comment by tnrclkr** [comment]
DID : F999 9363 5055 4254 9664 77

Brand : Beko
Model : 8807871200

**Comment by fotisbaco** [comment]
I wrote also my oven ID with the same installation problem

DID : F999904668828549174231

Brand : Grunding

Model : 7757782987

**Comment by rowysock** [comment]
@tnrclkr @fotisbaco Your devices should work after you upgrade to v0.2.2

@tnrclkr Your AC is more advanced than the one I tested the integration with. I've created an issue for more advanced features #71. It's going to be hard for me to implement those features without access to your AC

@fotisbaco You should be able to connect to your oven, but there are going to be oven features, that are not yet supported. Please create an issue to add them

**Comment by tnrclkr** [comment]
@rowysock managed with homewhiz app located in my house wifi connected. i can give you any app or direct access to device ( real ip remote etc.. ) but i dont know if this will help. Thanks for all you doin, really great comp.

**Comment by rowysock** [comment]
@tnrclkr Both app access and direct device access would be very helpful. please contact me at rowysock@gmail.com

**Comment by AlessandroAnnini** [comment]
@rowysock @tnrclkr I have the same error... did you manage to make it work?  
I am on version 0.4.0
