### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strKey'

### ISSUE THREAD

**Issue by TechHummel** [rowysock/home-assistant-HomeWhiz#77]
I do see some error messages with the latest version:

Washing machine 7165142200
```
Traceback (most recent call last):
  File "/config/custom_components/homewhiz/bluetooth.py", line 96, in handle_notify
    self.async_set_updated_data(full_message)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 346, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 121, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 381, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 97, in state
    if self.current_option is None or self.current_option not in self.options:
  File "/config/custom_components/homewhiz/select.py", line 174, in current_option
    return self.get_option(self.coordinator.data)
  File "/config/custom_components/homewhiz/select.py", line 45, in get_option
    return self.byte_to_option(clamp(data[self.read_index]))
  File "/config/custom_components/homewhiz/select.py", line 66, in byte_to_option
    return option.strKey
AttributeError: 'NoneType' object has no attribute 'strKey'
```

```
2022-12-27 17:36:52.498 INFO (MainThread) [custom_components.homewhiz] Setting up entry XX
2022-12-27 17:36:52.498 INFO (MainThread) [custom_components.homewhiz] Setting up bluetooth connection
2022-12-27 17:36:52.502 INFO (MainThread) [homeassistant.components.select] Setting up select.homewhiz
2022-12-27 17:36:52.510 INFO (MainThread) [homeassistant.components.climate] Setting up climate.homewhiz
2022-12-27 17:36:52.572 DEBUG (MainThread) [custom_components.homewhiz] Generating descriptions from config
2022-12-27 17:36:52.572 DEBUG (MainThread) [custom_components.homewhiz] Adding STATE EnumEntityDescription
2022-12-27 17:36:52.572 DEBUG (MainThread) [custom_components.homewhiz] Selects: ['STATE', 'WASHER_PROGRAM', 'WASHER_TEMPERATURE', 'WASHER_SPIN', 'WASHER_PREWASH', 'WASHER_EXTRARINSE', 'WASHER_FAST_PLUS', 'WASHER_HIDDEN_ANTI_CREASE', 'WASHER_STEAM', 'WASHER_DRY']
2022-12-27 17:36:52.629 DEBUG (MainThread) [custom_components.homewhiz] Appliance is not AC, not adding Climate entity
```
After homeassistant restart
```
2022-12-27 17:36:55.458 INFO (MainThread) [custom_components.homewhiz] Successfully connected. RSSI: -127
2022-12-27 17:36:55.607 DEBUG (MainThread) [custom_components.homewhiz] Message received: bytearray(b'\x02\x01\x00\x00')
2022-12-27 17:36:55.607 DEBUG (MainThread) [custom_components.homewhiz] Ignoring short message
2022-12-27 17:36:55.715 DEBUG (MainThread) [custom_components.homewhiz] Message received: bytearray(b'\x02\x04<\x00\x00\x009\x00\xb8d\x13\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x14\x80(\x0e\x00\x00\x00\x00\x00\x02\x14\x00\x00\x80\x80\x07\x00\x00\x00\x00\x00\x00')
2022-12-27 17:36:55.715 DEBUG (MainThread) [custom_components.homewhiz] Message index: 0
2022-12-27 17:36:55.757 DEBUG (MainThread) [custom_components.homewhiz] Message received: bytearray(b'\x02\x04\x18\x00\x01\x00\x15\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x13\x00\x00\x00\x00\x00\x00')
2022-12-27 17:36:55.758 DEBUG (MainThread) [custom_components.homewhiz] Message index: 1
2022-12-27 17:36:55.758 DEBUG (MainThread) [custom_components.homewhiz] Full message: bytearray(b'\x00\xb8d\x13\xab\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x14\x80(\x0e\x00\x00\x00\x00\x00\x02\x14\x00\x00\x80\x80\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x13\x00\x00\x00\x00\x00\x00')
2022-12-27 17:36:55.758 DEBUG (MainThread) [custom_components.homewhiz] Manually updated homewhiz data
``` 

Not sure if this is related but I can also select different states of my washing machine although this is not supported. 
![image](https://user-images.githubusercontent.com/15891478/209696064-15c280df-cecb-4c60-a966-d8d440e3dbca.png)

**Comment by rowysock** [comment]
What is your device digital ID?

**Comment by TechHummel** [comment]
Oh sorry, confused it with the model number....
F999 9067 0428 4043 6318 39
Maybe we should add a debug logging that spits out this id?

**Comment by rowysock** [comment]
good idea. I was also thinking about the GitHub issue template that would require users to provide the digital ID
