### ISSUE TITLE
Support for dishwasher consumableSettings

### ISSUE THREAD

**Issue by rowysock** [rowysock/home-assistant-HomeWhiz#92]
In dishwasher config there is consumableSettings section. We should handle it

```
"consumableSettings": {
    "consumables": [
      {
        "consumableType": "DETERGENT",
        "forms": [
          {
            "consumableForm": "TABLET",
            "lastCycleConsumptionAmountDataArrayReadIndex": 69
          },
          {
            "consumableForm": "LIQUID",
            "lastCycleConsumptionAmountDataArrayReadIndex": 73,
            "lastCycleConsumptionAmountFactor": 1.6,
            "warningSetting": {
              "wifiArrayReadIndex": 61,
              "bitIndex": 7
            }
          }
        ]
      },
      {
        "consumableType": "RINSE_AID",
        "forms": [
          {
            "consumableForm": "LIQUID",
            "lastCycleConsumptionAmountDataArrayReadIndex": 72,
            "lastCycleConsumptionAmountFactor": 1.5,
            "warningSetting": {
              "wifiArrayReadIndex": 61,
              "bitIndex": 0
            },
            "autoDosingAmountSetting": {
              "wifiArrayIndex": 64,
              "boundedValues": [
                {
                  "strKey": "",
                  "lowerLimit": 0,
                  "upperLimit": 4,
                  "step": 1,
                  "factor": 1,
                  "unit": ""
                }
              ]
            }
          }
        ]
      },
      {
        "consumableType": "SALT",
        "forms": [
          {
            "consumableForm": "POWDER",
            "lastCycleConsumptionAmountDataArrayReadIndex": 71,
            "warningSetting": {
              "wifiArrayReadIndex": 61,
              "bitIndex": 1
            }
          }
        ]
      }
    ]
  }
```

**Comment by Scorpio256** [comment]
Hello can I be some help? I have dishwasher. Also oficial app can notify you if you are low on detergent or rinser. That whould be cool to have in HA.

**Comment by rowysock** [comment]
Hi, @Scorpio256 your help would be very welcome :)

Can you figure out how to map `consumableSettings` to Home Assistant entities? https://developers.home-assistant.io/docs/core/entity

For washing machines, I've implemented warnings as a Binary Sensor Entity
But what about `lastCycleConsumptionAmountData` is this a read-only information?
Also what's the deal with autoDosingAmountSetting?

**Comment by TechHummel** [comment]
Would it be possible to create new entities for this on the fly? Say you switch from a tablet to a liquid detergent and then a new warning / binary entity is created.

**Comment by rowysock** [comment]
I don't know if removing entities from the integration is technically possible, but I don't think it is a good idea. I imagine HA automation complaining about missing entities. If we have binary sensor for warnings, we can just leave it "False".

Anyway in this case, consumableSettings.warningSetting is a duplicate of top-level warningSetting, so it should be already handled by #86

**Comment by rowysock** [comment]
As discussed with @Scorpio256 over email:

The part 
```
"lastCycleConsumptionAmountDataArrayReadIndex": 73,
"lastCycleConsumptionAmountFactor": 1.6,
```
Probably relates to the consumable amount section and should be represented as an sensor entity in HA
<img width="458" alt="consumableAmounts" src="https://user-images.githubusercontent.com/2960605/210272999-aec23a30-9573-427c-97ce-056ddfceb2dd.png">

The part
```
"autoDosingAmountSetting": {
  "wifiArrayIndex": 64,
  "boundedValues": [
    {
      "strKey": "",
      "lowerLimit": 0,
      "upperLimit": 4,
      "step": 1,
      "factor": 1,
      "unit": ""
    }
  ]
}
```
Most certainly relates to "Amount per cycle" section and should be represented in HA as a select entity
![image](https://user-images.githubusercontent.com/2960605/210273144-7d576004-871c-48e2-908d-679f342ebca9.png)

@Scorpio256 can you confirm?

**Comment by Scorpio256** [comment]
After updating to the latest version of the integration, the entities are starting to show data.
Unfortunately, no entities have been created for any of my dishwasher settings.
The dishwasher cannot be turned on via the integration, I have to turn it on manually and turn on the remote control. However, this is also how it behaves with the official app.
The following entities can be fully or partially controlled.

Extra Rinse - Can be turned on cannot be turned off
Fast+ - The dishwasher receives the signal but does not turn on (probably the correct washing program must be set)
Extra
Half Load - Can be switched on cannot be switched off
Program - Can be switched, you can see on the dishwasher that the programs are changing
State - The "running" state can be used to turn on the wash program completely but does not respond to other states and many of the states are more informative
Steamgloss - Can be switched on but cannot be switched off
Tray Wash - Can be turned on cannot be turned off
![image](https://user-images.githubusercontent.com/7922814/210274997-f9784c93-aa33-402b-b189-c133aa27e084.png)
![image](https://user-images.githubusercontent.com/7922814/210275012-19deab6a-1053-4abf-89f2-fb91c10ee5b0.png)

The sensors seem to show correctly the time remaining and how long the program is taking.
Sub-state - shows the current information what the dishwasher is doing once it starts washing.

However, notifications and information about refills are missing.
For example, now the app is reporting to me a lack of Detergent and the integration doesn't show that at all.

**Comment by rowysock** [comment]
Is your device ID F999961730155826793828?
I just tested and you should have the following entities in HA:
```
            "STATE",
            "PROGRAM",
            "SUB_STATE",
            "DISHWASHER_TRAYWASH",
            "DISHWASHER_FAST+",
            "DISHWASHER_STEAMGLOSS",
            "DISHWASHER_EXTRARINSE",
            "DISHWASHER_HALFLOAD",
            "DISHWASHER_DELAY",
            "DISHWASHER_DURATION",
            "DISHWASHER_REMAINING",
            "REMOTE_CONTROL",
            "DISHWASHER_WARNING_NO_RINSE_AID",
            "DISHWASHER_WARNING_NO_SALT",
            "DISHWASHER_WARNING_NO_WATER",
            "DISHWASHER_WARNING_CHECK_THE_FILTER",
            "DISHWASHER_WARNING_DOOR_IS_OPEN",
            "DISHWASHER_WARNING_CALL_SERVICE",
            "DISHWASHER_LIQUID_DETERGENT_LOW",
            "SETTING_AUTO_DOOR",
            "SETTING_DETERGENT_TYPE",
            "DISHWASHER_RINSE_AID_LEVEL",
            "DISHWASHER_WATER_HARDNESS",
            "SETTING_INNER_ILLUMINATION",
```
Maybe try reconfiguring the integration?

**Comment by rowysock** [comment]
I don't see any of the newly added entities in v0.3.0 on your screens. Maybe just restart the HA?

**Comment by Scorpio256** [comment]
I removed the device, restarted HA, added the device and still don't see any more entities.

**Comment by rowysock** [comment]
Can you share your login info at rowysock@gmail.com?

**Comment by rowysock** [comment]
<img width="327" alt="image" src="https://user-images.githubusercontent.com/2960605/210285272-16aeff34-01b1-4494-8966-d073e539c14e.png">
<img width="328" alt="image" src="https://user-images.githubusercontent.com/2960605/210285280-9dce7017-180f-40f8-a923-f1e2ced00007.png">
Checked on two separate HA instances. All entities are there

**Comment by Scorpio256** [comment]
Works fine with new version [v0.3.0](https://github.com/rowysock/home-assistant-HomeWhiz/releases/tag/v0.3.0)

**Comment by TechHummel** [comment]
@Scorpio256 Can this ticket then be closed or is there something else that doesn't work / is still missing?

**Comment by Scorpio256** [comment]
I think all good

**Comment by rowysock** [comment]
Entities described here are not yet implemented https://github.com/rowysock/home-assistant-HomeWhiz/issues/92#issuecomment-1369169776. @Scorpio256 please confirm that the described Entities match the original app

**Comment by elektrolitr** [comment]
Hello!

I have a WiFi dishwasher (Beko BDIN39640A) and I can confirm that the Entities match the values from the dishwasher and the App. 

And the issues I had: 

## data not refreshing

The data from dishwasher updates very irregularly. Mostly it happens when I open the DW in the app, and even then data may not update. Very rarely (maybe couple times per week) it updates by itself, but I can't get the idea what is triggering it. 

In the logs I see one entry related to HomeWhiz: 
`2023-02-04 19:47:14.003 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback async_track_point_in_utc_time.<locals>.run_action(<Job HassJobT...7f2bcde96710>>) at /usr/src/homeassistant/homeassistant/helpers/event.py:1310
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1325, in run_action
    hass.async_run_hass_job(job, utc_point_in_time)
  File "/usr/src/homeassistant/homeassistant/core.py", line 580, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1285, in utc_converter
    hass.async_run_hass_job(job, dt_util.as_local(utc_now))
  File "/usr/src/homeassistant/homeassistant/core.py", line 583, in async_run_hass_job
    return self.async_add_hass_job(hassjob, *args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 486, in async_add_hass_job
    task = self.loop.create_task(hassjob.target(*args))
TypeError: HomewhizCloudUpdateCoordinator.refresh_connection() takes 1 positional argument but 2 were given`

## GB locale missing

I'm using the GB locale on HASS and adding the Dishwasher I had windows without any text. I solved the issue by copying translation files "en" to "gb". Now it works fine

## incorrect instructions in the README.MD

I installed the extension manually (because it isn't available in HACS). First, I created the directory /custom_components/HomeWhiz as per README and it didn't work. The correct directory is /homewhiz (all lowercase)

I'm willing to commit to the project, but I'm totally new to HomeAssistant, GitHub and almost new to Python (experience limited to data analysis and such), so please don't have too much trust in me!
