### ISSUE TITLE
"Invocation of the climate/set_temperature service failed. HomeWhizClimateEntity.async_set_temperature() got an unexpected keyword argument 'entity_id'"

### ISSUE THREAD

**Issue by lorenzoter** [rowysock/home-assistant-HomeWhiz#98]
Hi, i have installed your integration.
I created an entity: "climate.condizionatore_sala_ac".
I can turn the unit on and off, but when I try to change the mode or temperature I get this error:

"Invocation of the climate/set_temperature service failed. HomeWhizClimateEntity.async_set_temperature() got an unexpected keyword argument 'entity_id'"

can i help you in any way or with some log?

**Comment by TechHummel** [comment]
Hi! 👋 
Some more logs (you can look at the readme file) would be helpful! Which version of homeassistant are you running?

**Comment by lorenzoter** [comment]
this is a log:

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/climate/init.py:613
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 15:54:57 (2 occurrences)
Last logged: 15:54:59

[547240187344] HomeWhizClimateEntity.async_set_temperature() got an unexpected keyword argument 'entity_id'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/climate/init.py", line 613, in async_service_temperature_set
await entity.async_set_temperature(**kwargs)
TypeError: HomeWhizClimateEntity.async_set_temperature() got an unexpected keyword argument 'entity_id'`

-------------

i use hassio...
Home Assistant 2023.1.4
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest

best regards ;)

**Comment by TechHummel** [comment]
Sorry for my late response! Could you also include some logs before this error occurred? Thanks 😄

**Comment by pasqualepalmaccio** [comment]
same issue
